# Generated by Django 3.2.8 on 2021-11-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thread_comment',
            new_name='ThreadComment',
        ),
    ]
