# Generated by Django 3.2.8 on 2021-12-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_rename_thread_comment_threadcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useridea',
            name='idea_content',
        ),
        migrations.AddField(
            model_name='useridea',
            name='idea_detail',
            field=models.CharField(default='アイデアの用途が入力されていません', max_length=300),
        ),
        migrations.AddField(
            model_name='useridea',
            name='idea_from',
            field=models.CharField(default='思いついたきっかけが入力されていません', max_length=300),
        ),
        migrations.AddField(
            model_name='useridea',
            name='idea_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useridea',
            name='idea_tag',
            field=models.CharField(default='タグが入力されていません', max_length=100),
        ),
        migrations.AddField(
            model_name='useridea',
            name='idea_target',
            field=models.CharField(default='ターゲットが入力されていません', max_length=300),
        ),
    ]
