# Generated by Django 3.2.8 on 2021-12-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_auto_20211202_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridea',
            name='idea_for',
            field=models.CharField(default='アイデアの用途が入力されていません', max_length=300),
        ),
        migrations.AlterField(
            model_name='useridea',
            name='idea_detail',
            field=models.CharField(default='アイデアの詳細が入力されていません', max_length=300),
        ),
    ]
