# Generated by Django 3.2.8 on 2021-12-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_auto_20211202_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useridea',
            name='idea_tag',
            field=models.CharField(default='タグが入力されていません', max_length=50),
        ),
    ]
