# Generated by Django 3.2.8 on 2021-12-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0005_alter_useridea_idea_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useridea',
            name='idea_tag',
            field=models.CharField(default='タグが入力されていません', max_length=30),
        ),
    ]
