# Generated by Django 3.2.8 on 2021-12-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0006_alter_useridea_idea_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadcomment',
            name='idea_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
