# Generated by Django 3.2.8 on 2021-12-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0007_threadcomment_idea_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadcomment',
            name='account_image',
            field=models.ImageField(default='https://cdn2.aprico-media.com/production/imgs/images/000/029/940/original.png?1553946576', null=True, upload_to='images/'),
        ),
    ]
