# Generated by Django 3.2.8 on 2021-12-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0008_threadcomment_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadcomment',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useridea',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
