# Generated by Django 3.2.8 on 2021-12-09 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0009_auto_20211209_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadcomment',
            name='like',
        ),
        migrations.RemoveField(
            model_name='useridea',
            name='like',
        ),
    ]
