# Generated by Django 3.2.8 on 2021-10-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='名無しユーザー', max_length=20),
        ),
    ]
