# Generated by Django 3.2.8 on 2021-11-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_user_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='名字', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='名前', max_length=20),
        ),
    ]
