# Generated by Django 3.2.8 on 2021-11-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20211113_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_image',
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='user_image'),
            preserve_default=False,
        ),
    ]
