# Generated by Django 3.2.8 on 2021-11-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20211128_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='http://img.kb-cdn.com/imgviewer/NVpIM2ptOHhYRzVmUk5rM1NrNlFxYVV6enV4aGk2UFRJMmxPckdDUUVNYkJLcGFGbVM1Q1Y1RHJwdVhMOUlUemJLZDYxUGR2VjFtVk1qV1l5UGpZYlhaZUtZQjU5S0t0QXMwNGhUVnR4ek4vMnRpeVZTR092c2lIdDhuZHdBZG1FZzZHaWxza2s1M3RveFJkbUdGeDhEbDFLbjBqOUtPdXFLVDRKRi9WRnlBYXVvWXRpcnRzSHRRV2E2RkI0TlhKMml2RHRWc0VzRlhlU1dYTFUybC8rMEdKai9rNUh0N1owZkM5bEhJYURDWT0=?square=0', upload_to='images/', verbose_name='user_image'),
        ),
    ]
