# Generated by Django 3.2.8 on 2021-11-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_user_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_image',
            new_name='account_image',
        ),
    ]
