# Generated by Django 3.2.8 on 2021-11-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_rename_user_image_user_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_image',
            field=models.ImageField(default='https://cdn2.aprico-media.com/production/imgs/images/000/029/940/original.png?1553946576', upload_to='images/'),
        ),
    ]
