# Generated by Django 3.2.8 on 2021-12-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_user_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_image',
            field=models.ImageField(default='https://cdn2.aprico-media.com/production/imgs/images/000/029/940/original.png?1553946576', null=True, upload_to='images/'),
        ),
    ]
