# Generated by Django 3.2.8 on 2021-11-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_auto_20211122_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishvideo',
            name='checkbox_1',
        ),
        migrations.RemoveField(
            model_name='englishvideo',
            name='checkbox_2',
        ),
        migrations.RemoveField(
            model_name='englishvideo',
            name='checkbox_3',
        ),
        migrations.AddField(
            model_name='userenglish',
            name='checkbox_1',
            field=models.CharField(default='unchecked', max_length=10),
        ),
        migrations.AddField(
            model_name='userenglish',
            name='checkbox_2',
            field=models.CharField(default='unchecked', max_length=10),
        ),
        migrations.AddField(
            model_name='userenglish',
            name='checkbox_3',
            field=models.CharField(default='unchecked', max_length=10),
        ),
    ]
