# Generated by Django 3.2.8 on 2021-10-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20211028_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermovie',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
