# Generated by Django 3.2.8 on 2021-11-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_usermovie_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovie',
            name='vote_rate',
            field=models.CharField(default='評価が入力されていません', max_length=2),
        ),
    ]
