# Generated by Django 3.2.8 on 2021-11-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_usermovie_vote_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovie',
            name='vote_rate',
            field=models.CharField(default='評価なし', max_length=2),
        ),
    ]
