# Generated by Django 3.2.8 on 2021-11-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_usermovie_vote_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovie',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
