# Generated by Django 3.2.8 on 2021-12-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_usermovie_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovie',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
