# Generated by Django 3.2.8 on 2021-12-09 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_usermovie_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermovie',
            name='like',
        ),
    ]
