# Generated by Django 3.2.8 on 2021-11-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_userbook_reviewaverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='summary',
            field=models.CharField(default='感想・要約が入力されていません', max_length=150),
        ),
    ]
