# Generated by Django 3.2.8 on 2021-11-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_userbook_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='vote_rate',
            field=models.CharField(default='評価が入力されていません', max_length=2),
        ),
    ]
