# Generated by Django 3.2.8 on 2021-11-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_userbook_vote_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='vote_rate',
            field=models.CharField(default='評価なし', max_length=2),
        ),
    ]
