# Generated by Django 3.2.8 on 2021-11-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_userbook_itemurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageUrl', models.CharField(max_length=50)),
                ('item_url', models.CharField(max_length=50)),
                ('video_id', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
