# Generated by Django 3.2.8 on 2021-11-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_bookapi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookapi',
            old_name='video_id',
            new_name='book_id',
        ),
    ]
