# Generated by Django 3.2.8 on 2021-12-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_rename_item_url_bookapi_item_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
